server:
  port: 9002

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/pinyougoudb?characterEncoding=utf-8&useSSL=true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:   # 分页插件配置
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
